name: Deploy service for production
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## 형상 다운로드 & DB 정보 파일 생성
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: touch ./src/main/resources/application-mongoprod.properties
      - run: echo "${{ secrets.DB_INFO }}" > ./src/main/resources/application-mongoprod.properties
      ## 빌드 ; -Pprod : prod Profile을 사용하여 빌드 ; -x test : test를 제외하고 빌드
      - name: Execute Gradle build
        run: ./gradlew build -Pprod -x test
      # jar SecureCopy to server
      - name: Deploy Prod use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./build/libs/*.jar"
          target: "/home/opc/"
          strip_components: 2

      - name: Transfer Deploy Script use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "deploy.sh"
          target: "/home/opc/"

      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: chmod +x /home/opc/deploy.sh && sh /home/opc/deploy.sh